[[boostpython]]
arch = "aarch64"
git-tree-sha1 = "b8a369995df3d27e9e4125f54290a98bbc1905cc"
os = "macos"

    [[boostpython.download]]
    sha256 = "543a2a5406b8e6ddb6d776db88a43cef1c0faed04c85ad0704ffdfae21adca40"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.aarch64-apple-darwin.tar.gz"
[[boostpython]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0863d72da6623a4e48f22a1f2c488a3aedccdb7e"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "a0b298785290b799c377e342d076730645a124334a6cfdb80b87440a3e21f06a"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.aarch64-linux-gnu-cxx03.tar.gz"
[[boostpython]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4e484d3533bf95ea4a4acb1174e22b8ad071d11"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "c1d6f14c30500bd9303a5c2a9857f2262cc38cf4a00cccf89c672e3bed8166aa"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.aarch64-linux-gnu-cxx11.tar.gz"
[[boostpython]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e3520100ab307787ec85c41f3b3128652f8aa47"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "d7a8682ffe8290e7d8543fa93a3379ce9f484432470df6b00870f590d07de9a2"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.aarch64-linux-musl-cxx03.tar.gz"
[[boostpython]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e41e33d6f7fbc7e6bf48aec71fcc4ce19b98561"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "49aeb2369b2f6709381e58da5adda75d5cadc636348567a9d4ae608a68848e07"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.aarch64-linux-musl-cxx11.tar.gz"
[[boostpython]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74b8789ee25bd3f874ceedfa2b323d5ad86f357c"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "0d3321151351772c812b3916415475c58b56dc9d2d61cae664aceb36b8248663"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[boostpython]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37bb859da81005f2dae1c4b390defb44f9142f35"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "ce79ed3ec0225c88719accfea3a97edc361a965fa970ab101bfc90aa27203492"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[boostpython]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a488c099bb4b489258322e507c8baf5cd30767c"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "7fb2f10a5c99724086d2b08357394668b1458244728b28bf85e67e2db9f99891"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[boostpython]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22acfcf8c2b7e8b1884f036c883048b3478fd7b7"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "fa88aacc460be4947dde7a7d44c0aee49da0f1101ffa57a7a7ea62d6e2b1c496"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[boostpython]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35ee313c8c4af9b98c7051dc8daa5d224edd6fa0"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "f350f43981fa8d119fe1fb78d4da424f45295b023ed9be234c50a1016de12269"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[boostpython]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "053bedc0e16be7f1f81a6e3567a8ca1ecee1ec60"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "1124f545ad793b821fc7687d4738b2e72b543514505959e29c68b93a15182505"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[boostpython]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf4dfe69449015b23b051e5376507c6c2e46e604"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "fcc1ac059e6d7ad2bcfc7fbf3fbe9933928d9cadcb32e8a6de6ea1418c2610cf"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[boostpython]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97ded48d9bba3e4b5c49715313a696cbdbf59979"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "a3a34d1ecc178101e45820aad6e7e362d7bf04b8c414099e0540f2eb37544480"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[boostpython]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ae3871c934a7d90a11b6701d2697c49d653405e"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "69c7f8ab8d38bdad131578e02a7dd69cdcc318865c82f7ed6bf4cdba5fbc20ee"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.i686-linux-gnu-cxx03.tar.gz"
[[boostpython]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a96e5780dad90b2bb80befccb4d8d5041439870"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "717e97c8082056e40747ea2406a9299d99a54462692197ea3aeab5b34ebdec55"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.i686-linux-gnu-cxx11.tar.gz"
[[boostpython]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09d22790601101a6b1cb6fc6ec72f9ee7c118788"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "f9b32989b57d2a51911498ee55e71f6427722e3c4a85869aa560103a1e6758a1"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.i686-linux-musl-cxx03.tar.gz"
[[boostpython]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57d77b8977bde8bb468a14c02899436bdd9c0a9e"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "99d7eacfcf99fd6ba524418fd1c4f9a92fe1ee1182c3eae83f9033e7f6de39d9"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.i686-linux-musl-cxx11.tar.gz"
[[boostpython]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43d1cd706371dd50d5d9d965e136a45d7545ee1c"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "0a3f433b458fd790026ec7887ee089e4bed433832b7654767404470781765723"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[boostpython]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec11f9d6c4f290444732816ce241459001babe79"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "a3283b80493675c34dd1dee21f6ee9539e7565da1c7f3b53d8662086a4af3ece"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[boostpython]]
arch = "x86_64"
git-tree-sha1 = "32ed6bfedd361eb8346132524f876dacc78c16ad"
os = "macos"

    [[boostpython.download]]
    sha256 = "2d7e98b017c9f93e97b5dbe45212edb445f2bd34ae73f57cf5ad31344be12d03"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.x86_64-apple-darwin.tar.gz"
[[boostpython]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "992ed7a38affed36c04430f0ba7be58be6a2d422"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "a441a13e6609a6f20f346a321ca49c019964dfe324aa1f612dbf266e30080735"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.x86_64-linux-gnu-cxx03.tar.gz"
[[boostpython]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1477cf0da8255fd9b96fe7559191b6ad9dc97727"
libc = "glibc"
os = "linux"

    [[boostpython.download]]
    sha256 = "f2483deaceb3e6d307a95e039d090bdbeb8836a17de266f21b9f197dab75d1ef"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.x86_64-linux-gnu-cxx11.tar.gz"
[[boostpython]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "276b5730656e7f4dee8d0b6ab5747c78b92c6c91"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "e537a9c722dd3387620171a4b04c62fa4346d281e1f86d6622aeb5ab5d1ee072"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.x86_64-linux-musl-cxx03.tar.gz"
[[boostpython]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "709ca9d7c8146de0bd45be0d4fe4453684ce7ec7"
libc = "musl"
os = "linux"

    [[boostpython.download]]
    sha256 = "d6760f3b3332c2b41e977cc5970f8ce1f0db9d81d5b1e8217fd8ead43d2f38a2"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.x86_64-linux-musl-cxx11.tar.gz"
[[boostpython]]
arch = "x86_64"
git-tree-sha1 = "3bd70c077c7417397b0a5c7663399ce742733e6e"
os = "freebsd"

    [[boostpython.download]]
    sha256 = "b9974405e68d0297c25fbad5924d2346b7870cd9fcff8f6a9f2cb9b073e6d678"
    url = "https://github.com/JuliaBinaryWrappers/boostpython_jll.jl/releases/download/boostpython-v1.79.0+0/boostpython.v1.79.0.x86_64-unknown-freebsd.tar.gz"
